server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.184.142:3306/study1?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: study1
    password: study1

mybatis-plus:
  global-config:
    # 是否控制台 print mybatis-plus 的 LOGO
    banner: true
  configuration:
    # 自动驼峰命名规则 默认true 如果您的数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
    map-underscore-to-camel-case: true
    # Mybatis一级缓存，默认为 SESSION
    local-cache-scope: session
    # 开启Mybatis二级缓存，默认为 true
    cache-enabled: true
    # sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
