server:
  port: 8082
spring:
  application:
    name: 'template-admin'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.184.142:3306/study1?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: study1
    password: study1


# dubbo 相关配置(dubbo 的配置不再以 Spring 开头)
dubbo:
  application:
    # 应用名称
    name: ${spring.application.name}
  protocol:
    # 协议端口
    port: 20880
    # 协议名称 默认使用协议为dubbo协议。
    name: dubbo
  # 注册中心信息
  registry:
    address: zookeeper://127.0.0.1:2181
    # 默认组
    group: dubbo
#  # 元数据中心
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
  consumer:
    # '*' 表示随机任意获取某一个版本的接口【灰度发布】
    version: '*'
    # 服务请求可以在指定时间内完成，指定时间内未完成立即失败
    # 10秒
    timeout: 10000
    # 作为消费启动时候发现没有服务提供者的时候报错
    check: true
    retries: 3

